CREATE TABLE `my_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` bigint NOT NULL COMMENT '订单号',
  `parent_order_id` bigint DEFAULT NULL COMMENT '父单号',
  `user_pin` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '用户标识',
  `user_phone` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '用户手机号码',
  `sku_no` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '商品编码',
  `sku_name` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '商品名称',
  `sku_num` int DEFAULT NULL COMMENT '商品数量',
  `order_status` tinyint DEFAULT NULL COMMENT '订单状态',
  `order_type` varchar(4) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '订单类型',
  `order_appoint_type` tinyint DEFAULT NULL COMMENT '业务类型',
  `order_total_amount` decimal(12,2) DEFAULT NULL COMMENT '订单总金额',
  `order_amount` decimal(12,2) DEFAULT NULL COMMENT '订单支付金额',
  `order_discount` decimal(12,2) DEFAULT NULL COMMENT '优化金额',
  `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
  `pay_way` tinyint DEFAULT NULL COMMENT '支付方式',
  `yn` tinyint DEFAULT '1' COMMENT '是否删除',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `unq_idx_my_order_id` (`order_id`) COMMENT '订单号',
  KEY `idx_my_order_user_pin` (`user_pin`) USING BTREE COMMENT '用户标识'
) ENGINE=InnoDB AUTO_INCREMENT=1376186898513960963 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='订单表';

CREATE TABLE `my_appoint_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_pin` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '用户标识',
  `order_id` bigint DEFAULT NULL COMMENT '订单号',
  `jd_appointment_id` bigint NOT NULL COMMENT '预约单号',
  `appointment_no` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '商家预约单号',
  `order_appoint_type` tinyint DEFAULT NULL COMMENT '业务类型',
  `appoint_source` tinyint DEFAULT NULL COMMENT '预约类型',
  `appoint_status` tinyint DEFAULT '0' COMMENT '预约状态',
  `order_status` tinyint DEFAULT '0' COMMENT '订单状态',
  `sku_no` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '商品编码',
  `sku_name` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '套餐名称',
  `sku_amount` decimal(12,2) DEFAULT NULL COMMENT '商品金额',
  `user_name` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '用户名称',
  `id_card_type` tinyint DEFAULT NULL COMMENT '证件类型',
  `id_card_no` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '证件号码',
  `user_appoint_phone` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '预约手机号码',
  `store_id` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '门店ID',
  `store_name` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '门店名称',
  `goods_id` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '商家套餐ID',
  `appoint_date` datetime DEFAULT NULL COMMENT '预约时间',
  `check_status` tinyint DEFAULT NULL COMMENT '到检状态',
  `check_date` datetime DEFAULT NULL COMMENT '到检时间',
  `report_status` tinyint DEFAULT NULL COMMENT '报告状态',
  `report_date` datetime DEFAULT NULL COMMENT '报告时间',
  `write_off_status` tinyint DEFAULT NULL COMMENT '核销状态',
  `write_off_time` datetime DEFAULT NULL COMMENT '核销时间',
  `expire_time` datetime DEFAULT NULL COMMENT '过期时间',
  `user_order_phone` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '用户手机号码',
  `company_no` bigint DEFAULT NULL COMMENT '公司编码',
  `user_id` bigint DEFAULT NULL COMMENT '员工唯一标识',
  `store_pay_amount` decimal(12,2) DEFAULT NULL COMMENT '门店结算价',
  `enterprise_cost_type` tinyint DEFAULT '0' COMMENT '是否升级套餐',
  `yn` tinyint DEFAULT '1' COMMENT '是否有效',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `unq_idx_my_jd_appointment_id` (`jd_appointment_id`) COMMENT '预约单号',
  KEY `idx_my_appoint_user_pin` (`user_pin`) USING BTREE COMMENT '用户标识',
  KEY `idx_my_appoint_company_user_id` (`company_no`,`user_id`) USING BTREE COMMENT '用户标识'
) ENGINE=InnoDB AUTO_INCREMENT=1376186904662810626 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='预约表';
